/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    AEmpty: typeof import('antdv-next')['Empty']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    AModal: typeof import('antdv-next')['Modal']
    APopconfirm: typeof import('antdv-next')['Popconfirm']
    AProgress: typeof import('antdv-next')['Progress']
    ARadioButton: typeof import('antdv-next')['RadioButton']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ASelect: typeof import('antdv-next')['Select']
    ASpin: typeof import('antdv-next')['Spin']
    ATag: typeof import('antdv-next')['Tag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
